{
  "_id": "69a569d7-3c64-4619-8eb9-2fd232355bc0",

  "userName": "tree-service-user@companieshouse.gov.uk",
  "password": "{AUTH_TREE_PASSWORD}",
  "authzRoles": [
    {
      "_ref": "internal/role/openidm-admin"
    }
  ],

  "accountStatus": "active",
  "effectiveRoles": [],
  "effectiveAssignments": [],
  "postalCode": null,
  "stateProvince": null,
  "postalAddress": null,
  "displayName": null,
  "description": "Tree Service User",
  "country": null,
  "city": null,
  "givenName": "Tree Service",
  "profileImage": null,
  "sn": "tree-service-user@companieshouse.gov.uk",
  "telephoneNumber": null,
  "mail": "tree-service-user@companieshouse.gov.uk",
  "isMemberOf": null,
  "frIndexedString1": "11111111111111111111111111111112",
  "frIndexedString3": "migrated",
  "frIndexedString4": null,
  "frIndexedString5": "webfiling",
  "frUnindexedString1": null,
  "frUnindexedString2": null,
  "frUnindexedString3": null,
  "frUnindexedString4": null,
  "frUnindexedString5": null,
  "frIndexedMultivalued1": [],
  "frIndexedMultivalued2": [],
  "frIndexedMultivalued3": [],
  "frIndexedMultivalued4": [],
  "frIndexedMultivalued5": [],
  "frUnindexedMultivalued1": [],
  "frUnindexedMultivalued2": [],
  "frUnindexedMultivalued3": [],
  "frUnindexedMultivalued4": [],
  "frUnindexedMultivalued5": [],
  "frIndexedDate1": null,
  "frIndexedDate2": null,
  "frIndexedDate3": null,
  "frIndexedDate4": null,
  "frIndexedDate5": null,
  "frUnindexedDate1": null,
  "frUnindexedDate2": null,
  "frUnindexedDate3": null,
  "frUnindexedDate4": null,
  "frUnindexedDate5": null,
  "frIndexedInteger1": null,
  "frIndexedInteger2": null,
  "frIndexedInteger3": null,
  "frIndexedInteger4": null,
  "frIndexedInteger5": null,
  "frUnindexedInteger1": null,
  "frUnindexedInteger2": null,
  "frUnindexedInteger3": null,
  "frUnindexedInteger4": null,
  "frUnindexedInteger5": null,
  "consentedMappings": [],
  "kbaInfo": [],
  "preferences": null,
  "aliasList": [],
  "memberOfOrgIDs": []
}